version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "email-verifier"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lymswyjj3k9w"
s3_prefix = "email-verifier"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
