# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-authoring.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  A system for validating email addresses of potential mailing list subscribers
  and adding them to a Simple Email Service contact list.
Parameters:
  ApiDomainName:
    Type: String
  ApiRouteKey:
    Type: String
  SenderEmailAddress:
    Type: String
  SenderName:
    Type: String
  SubscribersTableName:
    Type: String

Resources:
  EmailVerifier:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html#examples-makefile-identifier
    # https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html
    # https://github.com/aws-samples/sessions-with-aws-sam/tree/master/go-al2
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: main
      Runtime: go1.x
      Description: Coordinates between the API Gateway, DynamoDB, and SES
      Timeout: 5
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscribersTableName
        - SESCrudPolicy:
            IdentityName: !Select [ "1", !Split [ "@", !Ref SenderEmailAddress ] ]
      Tracing: Active
      Environment:
        Variables:
          SUBSCRIBERS_TABLE_NAME: !Ref SubscribersTableName
          SENDER_EMAIL_ADDRESS: !Ref SenderEmailAddress
          SENDER_NAME: !Ref SenderName
      Events:
        Subscribe:
          Type: HttpApi
          Properties:
            ApiId: !Ref EmailApi
            Path: /subscribe
            Method: POST
        Verify:
          Type: HttpApi
          Properties:
            ApiId: !Ref EmailApi
            Path: /verify
            Method: GET

  EmailApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref EmailApi
      DomainName: !Ref ApiDomainName
      ApiMappingKey: !Ref ApiRouteKey
      Stage: $default

  EmailApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefaultRouteSettings:
        # https://stackoverflow.com/a/70423772
        # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html
        ThrottlingRateLimit: 10
        ThrottlingBurstLimit: 100

Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EmailVerifierApi:
    Description: "API Gateway root URL for the EmailVerifier function"
    Value: !Sub "https://${ApiDomainName}/${ApiRouteKey}"
  EmailVerifierFunction:
    Description: "EmailVerifier Lambda function ARN"
    Value: !GetAtt EmailVerifier.Arn
  EmailVerifierFunctionIamRole:
    Description: "Implicit IAM Role created for EmailVerifier function"
    Value: !GetAtt EmailVerifierRole.Arn
  SenderEmailAddress:
    Description: "Sender email address"
    Value: !Ref SenderEmailAddress
