AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  A system for validating email addresses of potential mailing list subscribers
  and adding them to a Simple Email Service contact list.
Resources:
  EmailVerifier:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Description: Coordinates between the API Gateway, DynamoDB, and SES
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Tracing: Active
      Events:
        NewSubscriber:
          Type: HttpApi
          Properties:
            Path: /new
            Method: POST
        ValidateEmail:
          Type: HttpApi
          Properties:
            Path: /validate
            Method: GET
    Connectors:
      EmailsToVerifyDbConn:
        Properties:
          Destination:
            Id: EmailsToVerifyDb
          Permissions:
            - Read
            - Write
  EmailsToVerifyDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EmailsToVerify
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EmailVerifierApi:
    Description: "API Gateway root URL for the EmailVerifier function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  EmailVerifierFunction:
    Description: "EmailVerifier Lambda function ARN"
    Value: !GetAtt EmailVerifier.Arn
  EmailVerifierFunctionIamRole:
    Description: "Implicit IAM Role created for EmailVerifier function"
    Value: !GetAtt EmailVerifierRole.Arn
