# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-authoring.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Mailing list system providing address validation and unsubscribe URIs.
Parameters:
  ApiDomainName:
    Type: String
  ApiMappingKey:
    Type: String
  EmailDomainName:
    Type: String
  SenderName:
    Type: String
  SubscribersTableName:
    Type: String
  InvalidRequestPath:
    Type: String
  AlreadySubscribedPath:
    Type: String
  VerifyLinkSentPath:
    Type: String
  SubscribedPath:
    Type: String
  NotSubscribedPath:
    Type: String
  UnsubscribedPath:
    Type: String

Resources:
  EListMan:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html#examples-makefile-identifier
    # https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html
    # https://github.com/aws-samples/sessions-with-aws-sam/tree/master/go-al2
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: main
      Runtime: go1.x
      Description: Coordinates between the API Gateway, DynamoDB, and SES
      Timeout: 5
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscribersTableName
        - SESCrudPolicy:
            IdentityName: !Ref EmailDomainName
      Tracing: Active
      Environment:
        Variables:
          API_DOMAIN_NAME: !Ref ApiDomainName
          API_MAPPING_KEY: !Ref ApiMappingKey
          EMAIL_DOMAIN_NAME: !Ref EmailDomainName
          SENDER_NAME: !Ref SenderName
          SUBSCRIBERS_TABLE_NAME: !Ref SubscribersTableName
          INVALID_REQUEST_PATH: !Ref InvalidRequestPath
          ALREADY_SUBSCRIBED_PATH: !Ref AlreadySubscribedPath
          VERIFY_LINK_SENT_PATH: !Ref VerifyLinkSentPath
          SUBSCRIBED_PATH: !Ref SubscribedPath
          NOT_SUBSCRIBED_PATH: !Ref NotSubscribedPath
          UNSUBSCRIBED_PATH: !Ref UnsubscribedPath
      Events:
        Subscribe:
          Type: HttpApi
          Properties:
            ApiId: !Ref EListManApi
            Path: /subscribe/{email}
            Method: POST
        Verify:
          Type: HttpApi
          Properties:
            ApiId: !Ref EListManApi
            Path: /verify/{email}/{uid}
            Method: GET
        UnsubscribeGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref EListManApi
            Path: /unsubscribe/{email}/{uid}
            Method: Get
        UnsubscribePost:
          Type: HttpApi
          Properties:
            ApiId: !Ref EListManApi
            Path: /unsubscribe/{email}/{uid}
            Method: POST

  EListManApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref EListManApi
      DomainName: !Ref ApiDomainName
      ApiMappingKey: !Ref ApiMappingKey
      # https://github.com/aws/serverless-application-model/issues/192#issuecomment-520893111
      Stage: !Ref EListManApi.Stage

  EListManApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefaultRouteSettings:
        # https://stackoverflow.com/a/70423772
        # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html
        ThrottlingRateLimit: 10
        ThrottlingBurstLimit: 100

  EListManReceiptRuleSet:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptruleset.html
    Type: AWS::SES::ReceiptRuleSet

  EListManReceiptRuleSetPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt EListMan.Arn
      Principal: "ses.amazonaws.com"
      SourceArn: !Sub "arn:${AWS::Partition}:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/${EListManReceiptRuleSet}:receipt-rule/*"

  EListManUnsubscribeReceiptRule:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptrule.html
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Ref EListManReceiptRuleSet
      Rule:
        Name: EListManUnsubscribe
        Enabled: true
        TlsPolicy: Require
        ScanEnabled: true
        Recipients:
          - !Sub "unsubscribe@${EmailDomainName}"
        Actions:
          - LambdaAction:
              FunctionArn: !GetAtt EListMan.Arn
    DependsOn: EListManReceiptRuleSetPermission

Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EListManApi:
    Description: "API Gateway root URL for the EListMan function"
    Value: !Sub "https://${ApiDomainName}/${ApiMappingKey}"
  EListManFunction:
    Description: "EListMan Lambda function ARN"
    Value: !GetAtt EListMan.Arn
  EListManFunctionIamRole:
    Description: "Implicit IAM Role created for EListMan function"
    Value: !GetAtt EListManRole.Arn
  SenderEmailAddress:
    Description: "Sender email address"
    Value: !Sub "${SenderName} <no-reply@${EmailDomainName}>"
