// Code generated by "stringer -type=SubscriberStatus"; DO NOT EDIT.

package db

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unverified-0]
	_ = x[Verified-1]
}

const _SubscriberStatus_name = "UnverifiedVerified"

var _SubscriberStatus_index = [...]uint8{0, 10, 18}

func (i SubscriberStatus) String() string {
	if i < 0 || i >= SubscriberStatus(len(_SubscriberStatus_index)-1) {
		return "SubscriberStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubscriberStatus_name[_SubscriberStatus_index[i]:_SubscriberStatus_index[i+1]]
}
