// Code generated by "stringer -type=eventOperationType"; DO NOT EDIT.

package handler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Subscribe-1]
	_ = x[Verify-2]
	_ = x[Unsubscribe-3]
}

const _eventOperationType_name = "UndefinedSubscribeVerifyUnsubscribe"

var _eventOperationType_index = [...]uint8{0, 9, 18, 24, 35}

func (i eventOperationType) String() string {
	if i < 0 || i >= eventOperationType(len(_eventOperationType_index)-1) {
		return "eventOperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _eventOperationType_name[_eventOperationType_index[i]:_eventOperationType_index[i+1]]
}
