// Code generated by "stringer -type=OperationResult"; DO NOT EDIT.

package ops

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[AlreadySubscribed-1]
	_ = x[VerifyLinkSent-2]
	_ = x[Subscribed-3]
	_ = x[NotSubscribed-4]
	_ = x[Unsubscribed-5]
}

const _OperationResult_name = "InvalidAlreadySubscribedVerifyLinkSentSubscribedNotSubscribedUnsubscribed"

var _OperationResult_index = [...]uint8{0, 7, 24, 38, 48, 61, 73}

func (i OperationResult) String() string {
	if i < 0 || i >= OperationResult(len(_OperationResult_index)-1) {
		return "OperationResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationResult_name[_OperationResult_index[i]:_OperationResult_index[i+1]]
}
