name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: "Run Continuous Integration"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Install dependencies
        run: go get .

      - name: Run static checks
        run: |
          result="$(go fmt ./...)" && echo "$result" && [[ -z "$result" ]]
          go vet ./...
          go run honnef.co/go/tools/cmd/staticcheck ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -covermode=count ./...
